# Generated by Django 5.1.7 on 2025-05-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='is_reminded',
            field=models.BooleanField(default=False, help_text='리마인드가 완료되었는지 여부', verbose_name='리마인드 완료'),
        ),
        migrations.AddField(
            model_name='memo',
            name='reminder_date',
            field=models.DateTimeField(blank=True, help_text='메모를 리마인드 받을 날짜와 시간', null=True, verbose_name='리마인드 일시'),
        ),
    ]
